### Health Check
GET http://localhost:8080/healthz

### List Namespaces
GET http://localhost:8080/api/v1/namespaces

### List Deployments
GET http://localhost:8080/api/v1/namespaces/kube-system/deployments

### List Pods
GET http://localhost:8080/api/v1/namespaces/kube-system/pods

### Get Pod Details
GET http://localhost:8080/api/v1/namespaces/kube-system/pods/kube-scheduler-minikube

### List Namespace Events 
GET http://localhost:8080/api/v1/namespaces/kube-system/events

### List Namespace Events With Filter
GET http://localhost:8080/api/v1/namespaces/kube-system/events?involvedObjectName=etcd-minikube

### Get Pod Logs
GET http://localhost:8080/api/v1/namespaces/kube-system/pods/kube-scheduler-minikube/logs

### Get Pod Logs With Container
GET http://localhost:8080/api/v1/namespaces/kube-system/pods/kube-scheduler-minikube/logs?container=kube-scheduler

### Get Pod Logs With Tail Lines
GET http://localhost:8080/api/v1/namespaces/kube-system/pods/kube-scheduler-minikube/logs?tailLines=3

### Get Pod Logs With Container & Tail Lines
GET http://localhost:8080/api/v1/namespaces/kube-system/pods/kube-scheduler-minikube/logs?container=kube-scheduler&tailLines=3