name: Unit Tests
on:
  push:
jobs:
  web-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: '24.16'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Install dependencies
        working-directory: web
        run: npm ci
      - name: Run tests
        working-directory: web
        run: npm test
  api-tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v7
        - uses: actions/setup-go@v7
          with:
            go-version: '1.26.x'
            cache-dependency-path: api
        - name: Install dependencies
          working-directory: api
          run: go mod download
        - name: Build
          working-directory: api
          run: go build -v ./...
        - name: Run tests
          uses: robherley/go-test-action@v1
          with:
            moduleDirectory: api

